name: run unit tests
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.8
      - name: Setup JAVA JDK
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Test the project
        run: mvn package